AplikacjaIO/Controllers/MenuUzytkownikaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace AplikacjaIO.Controllers
{
    [Authorize]
    public class MenuUzytkownikaController : Controller
    {
        public ActionResult Index()
        {
            var role = ((ClaimsPrincipal)User).FindFirst(ClaimTypes.Role).Value;
            if(role == "Kierownik")
            {
                return RedirectToAction("Kierownik", "MenuUzytkownika");
            }
            else
            {
                return RedirectToAction("Kasjer", "MenuUzytkownika");
            }
        }
        [Authorize(Roles = "Kasjer")]
        // GET: MenuUzytkownika
        public ActionResult Kasjer()
        {
            return View();
        }

        [Authorize(Roles = "Kierownik")]
        public ActionResult Kierownik()
        {
            return View();
        }
    }
}

AplikacjaIO/Controllers/PromocjeController.cs
using DataServiceLayer.IService;
using DataServiceLayer.Models.View;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace AplikacjaIO.Controllers
{
    [Authorize(Roles = "Kierownik")]
    public class PromocjeController : Controller
    {
        private readonly IPromocja _promocja;

        public PromocjeController(IPromocja promocja)
        {
            _promocja = promocja;
        }

        // GET: Promocje
        public ActionResult Index()
        {
            var model = _promocja.GetPromocjaList();
            if(model == null)
            {
                model = new List<PromocjeModel>();
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult Wprowadz()
        {
            ViewBag.czyEdycja = false;
            ViewBag.czyPost = false;
            return View();
        }
        [HttpPost]
        public ActionResult Wprowadz(PromocjeModel model)
        {
            ViewBag.czyEdycja = false;
            var data = Request.Form.GetValues("DataWdrozenia");
            model.IdKierownika = Convert.ToInt32(((ClaimsPrincipal)User).FindFirst(ClaimTypes.NameIdentifier).Value);
             ViewBag.czyPost = true; 
            model = _promocja.Wprowadz(model);
            if(model == null)
            {
                ViewBag.Status = false;
            }
            else
            {
                ViewBag.Status = true;
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult Edytuj(int IdPromocji)
        {
            PromocjeModel model = _promocja.GetPromocje(IdPromocji);
            if(model == null)
            {
                return View("Index", _promocja.GetPromocjaList());
            }
            ViewBag.czyEdycja = true;
            ViewBag.czyPost = false;
            return View("Wprowadz", model);
        }
        [HttpPost]
        public ActionResult Edytuj(PromocjeModel model)
        {
            ViewBag.czyEdycja = true;
            ViewBag.czyPost = true;
            model.IdKierownika = Convert.ToInt32(((ClaimsPrincipal)User).FindFirst(ClaimTypes.NameIdentifier).Value);
            model = _promocja.Edycja(model);
            if(model == null)
            {
                ViewBag.Status = false;
            }
            else
            {
                ViewBag.Status = true;
            }
            return View("Wprowadz", model);
        }

        [HttpGet]
        public ActionResult Usun(int IdPromocji)//ewentulanie samo id promocji
        {
            ViewBag.CzyUsunieto = _promocja.Usun(IdPromocji);
            var model = _promocja.GetPromocjaList();
            return View("Index", model);
        }

    }
}

AplikacjaIO/Views/MenuUzytkownika/Kasjer.cshtml
@{
    ViewBag.Title = "Kasjer";
}
<div class="container">
    <div class="bgc">
        <div class="row">
            <div class="col-12">
                <strong>
                    <span class="TextLuna">Luna Express</span>
                </strong>
                <span class="PanelText">
                    Witaj w panelu zarządzania
                </span>
            </div>
        </div>
        <div class="row">
            <div class="col-6 marEntry">
                <span class="textEntry">
                    System zarządzania restauracja z jedzeniem na wage
                </span>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid FluidColor">
    <div class="container">
        <div class="row">
            <div class="col-1" style="bottom:35px;left:45px">
                <div class="halCIrcle"></div>
            </div>
        </div>

        <div class="row">
            <div class="col-12" style="text-align:center">
                <div>
                    <strong>
                        <span style="font-size:36px">
                            Kasjer
                        </span>
                    </strong>
                </div>
            </div>

        </div>

        <div class="row">
            <div class="col-12">
                <div>
                    <strong>
                        <span style="font-size:20px">
                            Wybierz Opcje:
                        </span>
                    </strong>
                </div>
            </div>
        </div>

        <div class="row marg400200 pad70bot TextMove">
            <div class="col-1">
                <div class="numberCircle">
                    1
                </div>
            </div>

            <div class="col-11 moveText">
               
                    <span>
                        <strong>@Html.ActionLink("Zarządzaj Rachunkami!", "index", "rachunki", null, new { @class = "KasjerKierownik" })</strong>
                    </span>
               
                <br />
                <span>
                    Tutaj możesz stworzyć nowy rachunek.
                </span>
            </div>
        </div>
    </div>
</div>

AplikacjaIO/Views/MenuUzytkownika/Kierownik.cshtml
@{
    ViewBag.Title = "Kierownik";
}
<div class="container">
    <div class="bgc">
        <div class="row">
            <div class="col-12">
                <strong>
                    <span class="TextLuna">Luna Express</span>
                </strong>
                <span class="PanelText">
                    Witaj w panelu zarządzania
                </span>
            </div>
        </div>
        <div class="row">
            <div class="col-6 marEntry">
                <span class="textEntry"> 
                    System zarządzania restauracja z jedzeniem na wage
                </span>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid FluidColor">
    <div class="container">
        <div class="row">
            <div class="col-1" style="bottom:35px;left:45px">
                <div class="halCIrcle"></div>
            </div>
        </div>

        <div class="row">
            <div class="col-12" style="text-align:center">
                <div>
                    <strong>
                        <span style="font-size:36px">
                            Kierownik
                        </span>
                    </strong>
                </div>
            </div>
            
        </div>

        <div class="row">
            <div class="col-12">
                <div>
                    <strong>
                        <span style="font-size:20px">
                            Wybierz Opcje:
                        </span>
                    </strong>
                </div>
            </div>
        </div>

        <div class="row marg400200 TextMove" >
            <div class="col-1">
                <div class="numberCircle">
                    1
                </div>
            </div>

            <div class="col-11 moveText">
                
                    <span>
                        <strong>@Html.ActionLink("Zarządzaj Promocjami!", "Index", "Promocje", null, new { @class = "KasjerKierownik" })</strong>
                    </span>
               
                <br />
                <span>
                    Tutaj możesz zarządzać wszystkim promocjami dodawać nowe, edytować lub usuwać już istniejące.
                </span>
            </div>
        </div>

        <div class="row marg400200 TextMove">
            <div class="col-1">
                <div class="numberCircle">
                    2
                </div>
            </div>

            <div class="col-11 moveText">
              
                    <span>
                        <strong>@Html.ActionLink("Zarządzaj Rachunkami!", "index", "rachunki", null, new { @class = "KasjerKierownik" })</strong>
                    </span>
              
                <br />
                <span>
                    Tutaj możesz zarządzać wszystkimi rachunkami przeglądać, edytować, usuwać lub drukowac istniejące
                </span>
            </div>
        </div>

        <div class="row pad70bot marg400200 TextMove">
            <div class="col-1">
                <div class="numberCircle">
                    3
                </div>
            </div>

            <div class="col-11 moveText">
              
                    <span>
                        <strong>@Html.ActionLink("Zarządzaj Raportami!", "index", "raporty", null, new { @class = "KasjerKierownik" })</strong>
                    </span>
               
                <br />
                <span>
                    Tutaj możesz zarządzać wszystkimi raportami dodawać nowe, przeglądać, edytować, usuwać lub drukowac istniejące
                </span>
            </div>
        </div>

    </div>
</div>