AplikacjaIO/Controllers/RachunkiController.cs
using DataServiceLayer.IService;
using DataServiceLayer.Models.View;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace AplikacjaIO.Controllers
{
    [Authorize]
    public class RachunkiController : Controller
    {
        private readonly IRachunki _rachunki;

        public RachunkiController(IRachunki rachunki)
        {
            _rachunki = rachunki;
        }
        // GET: Rachunki
        public ActionResult Index()
        {
            var model = _rachunki.GetRachunkiList();
            return View(model);
        }

        [Authorize(Roles = "Kasjer")]
        [HttpGet]
        public ActionResult Otworz()
        {
            var model = _rachunki.GetPromocje();
            return View(model);
        }

        [Authorize(Roles = "Kasjer")]
        [HttpPost]
        public ActionResult Zamknij()
        {
            var masa = Request.Form.Get("masa");
            var rabat = Request.Form.Get("sel");
            var idKasjera = Convert.ToInt32(((ClaimsPrincipal)User).FindFirst(ClaimTypes.NameIdentifier).Value);
            var model = _rachunki.Dodaj(masa, rabat,idKasjera);
            if(model == null)
            {
                ViewBag.Error = true;
            }
            return View("Zobacz", model);
        }

        [HttpGet]
        public ActionResult Zobacz(int IdRachunku)
        {
            var model = _rachunki.GetRachunek(IdRachunku);
            return View(model);
        }

        [Authorize(Roles = "Kierownik")]
        [HttpGet]
        public ActionResult Usun(int IdRachunku)
        {
            _rachunki.Usun(IdRachunku);
            var model = _rachunki.GetRachunkiList();
            return View("Index", model);
        }

    }
}

AplikacjaIO/Views/Rachunki/Index.cshtml
@model List<DataServiceLayer.Models.View.RachunkiModel>
@{
    ViewBag.Title = "Index";
}

<div class="container">
    <div class="row mar-top50">
        <table id="Promocje">
            <tr style="border-bottom:1px solid black;text-align:center;padding-bottom:10px;">
                <td style="width:33.3333%;border-right:1px solid black">
                    <strong style="font-size:20px;">@Html.LabelFor(model => model.FirstOrDefault().IdRachunku)</strong>
                </td>
                <td style="width:33.3333%;border-right:1px solid black">
                    <strong style="font-size:20px;">@Html.LabelFor(model => model.FirstOrDefault().Wysokosc)</strong>
                </td>
                <td style="width:33.3333%;border-right:1px solid black">
                    <strong style="font-size:20px;">@Html.LabelFor(model => model.FirstOrDefault().DataRachunku)</strong>
                </td>
                <td></td>
            </tr>
            @for (int i = 0; i < Model.Count; i++)
            {
                <tr class="spacer"></tr>
                    <tr style="text-align:center;border-top:1px solid black;">
                        <td style="padding-top:10px;padding-bottom:10px;">
                            @Html.DisplayFor(model => model[i].IdRachunku, new { htmlAttributes = new { @class = "form-control intro-input" } })
                        </td>
                        <td style="padding-top:10px;padding-bottom:10px;">
                            @Html.DisplayFor(model => model[i].Wysokosc, new { htmlAttributes = new { @class = "form-control intro-input" } })
                        </td>
                        <td style="padding-top:10px;padding-bottom:10px;">
                            @Html.DisplayFor(model => model[i].DataRachunku, new { htmlAttributes = new { @class = "form-control intro-input" } })
                        </td>
                        <td style="padding-top:10px;padding-bottom:10px;">
                               @if (((System.Security.Claims.ClaimsPrincipal)User).FindFirst(System.Security.Claims.ClaimTypes.Role).Value == "Kierownik")
                               {
                                @Html.ActionLink("Usuń", "usun", "Rachunki", new { IdRachunku = Model[i].IdRachunku }, new { @class = "btn btn-danger btn-block" })
                               }
                           
                            @Html.ActionLink("Zobacz", "Zobacz", "Rachunki", new { IdRachunku = Model[i].IdRachunku }, new { @class = "btn btn-success" })
                        </td>
                    </tr>
            }
        </table>
    </div>



    @if (((System.Security.Claims.ClaimsPrincipal)User).FindFirst(System.Security.Claims.ClaimTypes.Role).Value == "Kasjer")
    {
        <div class="row mar-top50">
            <div class="col-12">
                @Html.ActionLink("Otworz", "Otworz", "Rachunki", null, new { @class = "btn btn-primary" })
            </div>
        </div>
    }
</div>

AplikacjaIO/Views/Rachunki/Otworz.cshtml
@model List<DataServiceLayer.Models.View.RachunkiSaveModel>
@{
    ViewBag.Title = "Otworz";
}


@using (Html.BeginForm("Zamknij", "Rachunki", FormMethod.Post))
    {
<div class="container-fluid" style="background-color:#dadada">
    <div class="container">
        <div class="row">
            <div class="col-12" style="font-family:Arial, Helvetica, sans-serif">
                <span style="font-size:36px"><strong>Nowy Rachunek!</strong></span>
            </div>
        </div>
        <table id="table">
            <tr style="border-bottom:1px solid black;text-align:center;padding-bottom:10px;">
                <td style="width:15%;border-right:1px solid black">
                    @*<strong style="font-size:20px;">@Html.LabelFor(model => model.FirstOrDefault().IdRachunku)</strong>*@
                    <strong><span>Numer Pozycji</span></strong>
                </td>
                <td style="width:40.3333%;border-right:1px solid black">
                    @*<strong style="font-size:20px;">@Html.LabelFor(model => model.FirstOrDefault().Wysokosc)</strong>*@
                    <strong><span>Waga(g)</span></strong>
                </td>
                <td style="width:45.3333%;border-right:1px solid black">
                    @*<strong style="font-size:20px;">@Html.LabelFor(model => model.FirstOrDefault().DataRachunku)</strong>*@
                    <strong><span>Cena(3.49zl/100g)</span></strong>
                </td>
            </tr>
            <tr>
                <td class="center">
                    <input type="text" class="form-control waga" value="0" name="masa" id="waga1" />
                </td>

                <td>
                    <input type="text" placeholder="Cena" id="cena1" class="form-control" disabled/>
                </td>

                <td>
                    <button type="button"></button>
                </td>

            </tr>
        </table>
        <div class="row">
            <div class="col-12" style="">

                <div class="row">
                    <div style="width:56%">

                    </div>
                    <div class="" style="width:12%">
                        <div style="border-top:1px solid black">
                            <span>Suma:</span>
                            <input type="number" id="suma12" style="background-color:transparent;border:none;width:70px" value="0" disabled />zł
                            
                        </div>
                    </div>
                    <div style="width:12%">
                        <select id="sel" class=form-control name="sel">
                            @for(int i = 0; i < Model.Count; i++)
                            {
                                <option value="@Model[i].Rabat">@Model[i].NazwaPromocji</option>
                            }
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <input  type="submit" class="btn btn-primary" value="Zamknij Rachunek">
            </div>
        </div>
    </div>
</div>

}
@section Scripts {

    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"></script>
    <script>
        var tables = document.getElementsByTagName('table');
        var table = tables[tables.length - 1];
        var rows = table.rows;
        for (var i = 0, td; i < rows.length; i++) {
            if (i != 0)
            {
                td = document.createElement('td');
                td.appendChild(document.createTextNode(i));
                rows[i].insertBefore(td, rows[i].firstChild);
            }

        }
        $(document).ready(function () {

            if ("tr:last") {
                $('button').addClass("btn btn-primary");
                $('button').attr("id", 'poz1');
                $('button').html('Usuń');


            }
            $('#poz').click(myFun());

            $('body').on("click", ".usun", function () {
                var ide = $(this).attr("id");
                if (ide.length > 5) {
                    var lastChar = ide.substr(ide.length - 2);

                }
                else if (ide.length > 6) {
                    var lastChar = ide.substr(ide.length - 3);
                }
                else {
                    var lastChar = ide.substr(ide.length - 1);
                }
                $('#tr' + lastChar).remove();
                $('tr:gt(0) td:first-child').remove();
                var tables = document.getElementsByTagName('table');
                var table = tables[tables.length - 1];
                var rows = table.rows;
                for (var i = 0, td; i < rows.length; i++) {
                    if (i != 0) {
                        td = document.createElement('td');
                        td.appendChild(document.createTextNode(i));
                        rows[i].insertBefore(td, rows[i].firstChild);
                        
                    }
                    $("tr:eq(" + i + ")").attr('id', "tr"+i);
                }

                var len = rows.length - 1;
                $('.btn-primary').attr('id', 'poz' + len);

               
            });

            $("body").on("focusout", ".waga", function () {

                var ide = $(this).attr("id");
                var lastChar = ide.substr(ide.length - 1);
                if (ide.length > 5) {
                    var lastChar = ide.substr(ide.length - 2);

                }
                else if (ide.length > 6) {
                    var lastChar = ide.substr(ide.length - 3);
                }
                else {
                    var lastChar = ide.substr(ide.length - 1);
                }
                $("#cena" + lastChar).val(($(this).val() * 3.49 / 100).toFixed(2));
                var suma = 0;
                $("input[name=masa]").each(function () {

                    suma = (suma + parseFloat($(this).val() * (3.49 / 100)));

                });
                $("#suma12").val(suma.toFixed(2));

            });

            $("body").on('change', "#sel", function () {
                var suma = 0;
                $("input[name=masa]").each(function () {

                    suma = (suma + parseFloat($(this).val() * (3.49 / 100)));

                });
                if ($(this).val() != 1)
                {
                    var c = suma * $(this).val() / 100;
                    var d = suma - c;
                }
                else
                {
                    var d = suma;
                }

                $("#suma12").val(d.toFixed(2));
            });

        });
        function myFun() {
            $("body").on('click', ".btn-primary", function () {
                
                $(this).removeClass('btn btn-primary');
                $(this).attr('value', 'Usuń');
                $(this).attr('onclick', '').unbind('click');
                $(this).attr('onclick', 'usun()').bind('click');
                $(this).addClass('btn btn-danger btn-block usun');
                $(this).attr('id', "usun" + (rows.length - 2))
               
            });
            var c = $('<td><input type="text" placeholder="Cena" class="form-control" id="cena' + (rows.length) + '" disabled /></td>')
           $('<tr id="tr' + (rows.length) + '" " ><td>' + rows.length + "</td></tr>").insertAfter("tr:last");
            var r = $('<td><input type="button" id="poz' + (rows.length - 1) + '"  onClick="myFun()" class="btn btn-primary" value="Dodaj pozycję"/></td>');
            var v = $('<td><select id="sel" class=form-control><option value=1>Brak Rabatu</option><option value=30>Studencki</option><option value=25>Wieczorna</option></select></td>');
            var w = $('<td><input type="text" value="0" name="masa" id="waga' + (rows.length - 1) + '"  class="form-control waga" " /></td>')

            $(w).insertAfter("td:last");
            $(w).addClass("waga");
            $(c).insertAfter("td:last");
            //$(r).attr('id', 'poz');
            $(r).insertAfter("td:last")
            var len = rows.length - 2;
            $('#poz' + len).removeClass('btn btn-primary');
            $('#poz' + len).attr('value', 'Usuń');
            $('#poz' + len).attr('onclick', '').unbind('click');
            $('#poz' + len).attr('onclick', 'usun()').bind('click');
            setTimeout(function () {
                $('#poz' + len).addClass('btn btn-danger btn-block usun');
                $('#poz' + len).attr('id', "usun" + (rows.length - 2))
            }, 5);






        }
  

    </script>

}

AplikacjaIO/Views/Rachunki/Wybierz.cshtml
@{
    ViewBag.Title = "Wybierz";
}
@using (Html.BeginForm("Zobacz", "Rachunki", FormMethod.Get))
{




        <div class="container">
            <div class="row">
                <div class="col-12" style="margin-top:4.5%;text-align:center">
                    <h3>Wybierz rachunek do podglądu!</h3>
                </div>
            </div>
            <div class="jumbotron" style="margin-top:4.5%">
                <div class="row">
                    <div class="col-12" style="margin-top:4.5%;text-align:center">
                        <h2>Podaj ID Rachunku!</h2>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div style="text-align:center">
                        @*@Html.TextBox("IdRachunku", "", new { @class = "form-control", @id = "IdRachunku" })*@
                            <input type="text" class="form-control" name="IdRachunku" id="IdRachunku" style="display:inline"/>
                        </div>
            
                    </div>
                    
                </div>
                <div class="row">
                    <div class="col-12" style="text-align:center">
                        <button type="submit" class="btn btn-primary">Zobacz</button>
                    </div>
                </div>
            </div>
        </div>



}

AplikacjaIO/Views/Rachunki/Zobacz.cshtml
@model DataServiceLayer.Models.View.RachunkiModel
@{
    ViewBag.Title = "Zobacz";
}


<div class="container-fluid">
    @if (ViewBag.Error != null)
    {
        if (ViewBag.Error == true)
        {
            <div class="container">
                <div class="row" style="margin-top:2.5%;margin-bottom:5%">
                    <div class="col-12" style="font-family:Arial, Helvetica, sans-serif">
                        <span style="font-size:32px;color:red"><strong>Blad przy zapisywaniu rachunku.\nSpróbuj ponownie</strong></span>
                    </div>
                </div>
            </div>
        }
        else
        {
            <div class="container">
                <div class="row" style="margin-top:2.5%;margin-bottom:5%">
                    <div class="col-12" style="font-family:Arial, Helvetica, sans-serif">
                        <span style="font-size:32px;color:lawngreen"><strong>Zapisano rachunek!</strong></span>
                    </div>
                </div>
            </div>
        }
    }
    <div class="container">
        <div class="row" style="border-bottom:1px solid black">
            <div class="col-3" style="border-right:1px solid black;text-align:center">
                <strong style="font-size:20px;">@Html.LabelFor(model => model.IdRachunku)</strong>
            </div>
            <div class="col-3" style="border-right:1px solid black;text-align:center">
                <strong style="font-size:20px;">@Html.LabelFor(model => model.Wysokosc)</strong>
            </div>
            <div class="col-3" style="border-right:1px solid black;text-align:center">
                <strong style="font-size:20px;">@Html.LabelFor(model => model.DataRachunku)</strong>
            </div>
            <div class="col-3" style="border-right:1px solid black;text-align:center">
                <strong style="font-size:20px;">@Html.LabelFor(model => model.NazwaKasjera)</strong>
            </div>

        </div>
        <div class="row">
            <div class="col-3" style="text-align:center">
                @Html.DisplayFor(model => model.IdRachunku, new { htmlAttributes = new { @class = "form-control intro-input" } })
            </div>

            <div class="col-3" style="text-align:center">
                @Html.DisplayFor(model => model.Wysokosc, new { htmlAttributes = new { @class = "form-control intro-input" } })
            </div>

            <div class="col-3" style="text-align:center">
                @Html.DisplayFor(model => model.DataRachunku, new { htmlAttributes = new { @class = "form-control intro-input" } })
            </div>

            <div class="col-3" style="text-align:center">
                @Html.DisplayFor(model => model.NazwaKasjera, new { htmlAttributes = new { @class = "form-control intro-input" } })
            </div>
        </div>
    </div>
</div>


<div class="container-fluid" style="text-align:center;margin-top:20px;">
    <div class="container">
        <div class="row">
            <table style="border:1px solid black">
                <tr style="border:1px solid black">
                    <td style="width:30%;border:1px solid black">
                        <strong style="font-size:20px;">@Html.LabelFor(model => model.Sklad.FirstOrDefault().Ilosc)</strong>
                    </td>
                    <td style="width:30%;border:1px solid black"> 
                        <strong style="font-size:20px;">@Html.LabelFor(model => model.Sklad.FirstOrDefault().Cena)</strong>
                    </td>
                </tr>
                @for (int i = 0; i < Model.Sklad.Count; i++)
                {
                    <tr style="border:1px solid black">
                        <td style="width:30%;border:1px solid black">
                            @Html.DisplayFor(model => model.Sklad[i].Ilosc, new { htmlAttributes = new { @class = "form-control intro-input" } })
                        </td>
                        <td style="width:30%;border:1px solid black">
                            @Html.DisplayFor(model => model.Sklad[i].Cena, new { htmlAttributes = new { @class = "form-control intro-input" } })
                        </td>
                    </tr>
                }
            </table>
        </div>
    </div>

</div>