AplikacjaIO/Controllers/RaportyController.cs
using DataServiceLayer.IService;
using DataServiceLayer.Models.View;
using DataServiceLayer.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AplikacjaIO.Controllers
{
    [Authorize(Roles = "Kierownik")]
    public class RaportyController : Controller
    {
        private readonly IRaporty _raporty;

        public RaportyController(IRaporty raporty)
        {
            _raporty = raporty;
        }
        // GET: Raporty
        public ActionResult Index()
        {
            var model = _raporty.GetRaportList();
            return View(model);
        }

        [HttpGet]
        public ActionResult Utworz()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Utworz(RaportModel model)
        {
            model = _raporty.Utworz(model);
            ViewBag.czyPostBack = true;
            if(model == null)
            {
                ViewBag.Error = true;
                return View();
            }
            return View(model);
        }

        public ActionResult Zobacz(int IdRaportu)
        {
            var model = _raporty.GetRaport(IdRaportu);
            return View(model);
        }

        public ActionResult Usun(int IdRaportu)
        {
            _raporty.Usun(IdRaportu);
            var model = _raporty.GetRaportList();
            return View("Index",model);
        }
    }
}

AplikacjaIO/Views/Raporty/Index.cshtml
@model List<DataServiceLayer.Models.View.RaportModel>
@{
    ViewBag.Title = "Index";
}

<div class="container">
    <div class="row mar-top50">
        <table id="Promocje">
            <tr style="border-bottom:1px solid black;text-align:center;padding-bottom:10px;">
                <td style="width:23%;border-right:1px solid black">
                    <strong style="font-size:20px;">@Html.LabelFor(model => model.FirstOrDefault().IdRaportu)</strong>
                </td>
                <td style="width:23%;border-right:1px solid black">
                    <strong style="font-size:20px;">@Html.LabelFor(model => model.FirstOrDefault().Suma)</strong>
                </td>
                <td style="width:23%;border-right:1px solid black">
                    <strong style="font-size:20px;">@Html.LabelFor(model => model.FirstOrDefault().DataOd)</strong>
                </td>
                <td style="width:23%;border-right:1px solid black">
                    <strong style="font-size:20px;">@Html.LabelFor(model => model.FirstOrDefault().DataDo)</strong>
                </td>
                <td></td>
            </tr>
            @for (int i = 0; i < Model.Count; i++)
            {
                <tr class="spacer"></tr>
                <tr style="text-align:center;border-top:1px solid black;border-bottom: 1px solid black">
                    <td style="padding-top:10px;padding-bottom:10px;">
                        @Html.DisplayFor(model => model[i].IdRaportu, new { htmlAttributes = new { @class = "form-control intro-input" } })
                    </td>
                    <td style="padding-top:10px;padding-bottom:10px;">
                        @Html.DisplayFor(model => model[i].Suma, new { htmlAttributes = new { @class = "form-control intro-input" } })
                    </td>
                    <td style="padding-top:10px;padding-bottom:10px;">
                        @Html.DisplayFor(model => model[i].DataOd, new { htmlAttributes = new { @class = "form-control intro-input" } })
                    </td>
                    <td style="padding-top:10px;padding-bottom:10px;">
                        @Html.DisplayFor(model => model[i].DataDo, new { htmlAttributes = new { @class = "form-control intro-input" } })
                    </td>
                    <td style="padding-top:10px;padding-bottom:10px;">
                        @Html.ActionLink("Usuń", "Usun", "Raporty", new { IdRaportu = Model[i].IdRaportu }, new { @class = "btn btn-danger btn-block" })
                        @Html.ActionLink("Zobacz", "Zobacz", "Raporty", new { IdRaportu = Model[i].IdRaportu }, new { @class = "btn btn-success btn-block" })
                        @*@Html.ActionLink("Edytuj", "Edytuj", "Raporty", new { IdPromocji = Model[i].IdRaportu }, new { @class = "btn btn-success" })*@
                    </td>
                </tr>
            }
        </table>
      
    </div>
    <div class="row mar-top50">
        <div class="col-12">
            @Html.ActionLink("Utwórz nowy", "Utworz", "Raporty", null, new { @class = "btn btn-primary" })
        </div>
    </div>
</div>

AplikacjaIO/Views/Raporty/Utworz.cshtml
@model DataServiceLayer.Models.View.RaportModel

@{
    string akcja = "Utworz";


    if (ViewBag.czyPostBack == true)
    {
        if (ViewBag.Error == true)
        {
            <div>
                "Bład przy próbie utworzenia raportu!"
            </div>
        }
        else
        {
            <div>
                Raport utworzony pomyslnie!
            </div>
        }
    }
    using (Html.BeginForm(akcja, "Raporty", FormMethod.Post))
    {
        <div class="container-fluid">
            <div class="container">

                <div class="row marg200200">
                    <div class="col-md-3 col-12">
                        <strong>@Html.LabelFor(Model => Model.DataOd , htmlAttributes: new { @class = "control-label labelIntro" })</strong>
                    </div>
                    <div class="col-md-3 col-12">
                        @Html.EditorFor(Model => Model.DataOd, new { htmlAttributes = new { @class = "form-control intro-input utworz", @id = "datepick2", @type="date" } })
                        <input type="hidden" id="alternate2" />
                        @Html.ValidationMessageFor(model => model.DataOd, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="row marg200200">
                    <div class="col-md-3 col-6">
                        <strong>@Html.LabelFor(Model => Model.DataDo, htmlAttributes: new { @class = "control-label labelIntro"})</strong>
                       
                    </div>
                    <div class="col-md-3 col-6">
                        @Html.EditorFor(Model => Model.DataDo, new { htmlAttributes = new { @class = "form-control intro-input utworz", @id = "datepick", @type = "date" } })
                        <input type="hidden" id="alternate" />
                        @Html.ValidationMessageFor(model => model.DataDo, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
        if (Model != null)
        {
            <div class="container-fluid">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            @Html.HiddenFor(model => model.IdRaportu)
                            <button type="submit" class="btn btn-primary">Zapisz Zmiany</button>
                        </div>
                    </div>
                </div>
            </div>
            @*<input type="submit" value="Zapisz zmiany">*@
            //button do usuniecia
        }
        else
        {
            <div class="container-fluid">
                <div class="container">
                    <div class="row">
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary">Stwórz</button>
                        </div>
                    </div>
                </div>
            </div>
        }
    }

}
@section Scripts {

 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">
<!-- jQuery first, then Tether, then Bootstrap JS. -->

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"></script>
<!-- datepicker -->
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="/resources/demos/style.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script type="text/javascript">


    $(document).ready(function () {
        $("#datepick").click(function () { $("#datepick").datepicker('show'); });
        $("#datepick2").click(function () { $("#datepick2").datepicker('show'); });
    });
    if (!Modernizr.inputtypes.date) {
        $("#datepick").datepicker({
            buttonText: "Select",
            showOn: "button",
            buttonImage: "https://jqueryui.com/resources/demos/datepicker/images/calendar.gif",
            dateFormat: 'mm/dd/yy',
            altFormat: "yy-mm-dd",
            altField: '#alternate'
        });
    } else {
        $('#datepick').on('change', function () {
            $('#alternate').val(this.value);
        });
    }
    if (!Modernizr.inputtypes.date) {
        $("#datepick2").datepicker({
            buttonText: "Select",
            showOn: "button",
            buttonImage: "https://jqueryui.com/resources/demos/datepicker/images/calendar.gif",
            dateFormat: 'mm/dd/yy',
            altFormat: "yy-mm-dd",
            altField: '#alternate2'
        });
    } else {
        $('#datepick2').on('change', function () {
            $('#alternate2').val(this.value);
        });
    }
</script>

}

AplikacjaIO/Views/Raporty/Zobacz.cshtml
@model DataServiceLayer.Models.View.RaportModel
@{
    ViewBag.Title = "Zobacz";
}




<div class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-12" style="margin-top:4.5%;margin-bottom:3%;text-align:center">
                <h3>Raport!</h3>
            </div>
        </div>
        <div class="row" style="border-bottom:1px solid black">
            <div class="col-3" style="border-right:1px solid black;border-left:1px solid black;text-align:center">
                <strong style="font-size:20px;">@Html.LabelFor(model => model.IdRaportu)</strong>
            </div>
            <div class="col-3" style="border-right:1px solid black;text-align:center">
                <strong style="font-size:20px;">@Html.LabelFor(model => model.Suma)</strong>
            </div>
            <div class="col-3" style="border-right:1px solid black;text-align:center">
                <strong style="font-size:20px;">@Html.LabelFor(model => model.DataOd)</strong>
            </div>
            <div class="col-3" style="border-right:1px solid black;text-align:center">
                <strong style="font-size:20px;">@Html.LabelFor(model => model.DataDo)</strong>
            </div>

        </div>
        <div class="row">
            <div class="col-3" style="text-align:center;font-size:20px">
                @Html.DisplayFor(model => model.IdRaportu, new { htmlAttributes = new { @class = "form-control intro-input" } })
            </div>

            <div class="col-3" style="text-align:center;font-size:20px">
                @Html.DisplayFor(model => model.Suma, new { htmlAttributes = new { @class = "form-control intro-input" } })
            </div>

            <div class="col-3" style="text-align:center;font-size:20px">
                @Html.DisplayFor(model => model.DataDo, new { htmlAttributes = new { @class = "form-control intro-input" } })
            </div>

            <div class="col-3" style="text-align:center;font-size:20px">
                @Html.DisplayFor(model => model.DataDo, new { htmlAttributes = new { @class = "form-control intro-input" } })
            </div>
        </div>
    </div>
</div>


<div class="container-fluid" style="text-align:center;margin-top:20px;">
    <div class="container">
        <div class="row">
            <table style="border:1px solid black">
                <tr style="border:1px solid black">
                    <td style="width:30%;border:1px solid black">
                        <strong style="font-size:20px;">@Html.LabelFor(model => model.RachunkiNaRaporcie.FirstOrDefault().IdRachunku)</strong>
                    </td>
                    <td style="width:30%;border:1px solid black">
                        <strong style="font-size:20px;">@Html.LabelFor(model => model.RachunkiNaRaporcie.FirstOrDefault().Wysokosc)</strong>
                    </td>
                    <td style="width:30%;border:1px solid black">
                        <strong style="font-size:20px;">@Html.LabelFor(model => model.RachunkiNaRaporcie.FirstOrDefault().DataRachunku)</strong>
                    </td>
                    <td style="width:30%;border:1px solid black">
                        <strong style="font-size:20px;">@Html.LabelFor(model => model.RachunkiNaRaporcie.FirstOrDefault().NazwaKasjera)</strong>
                    </td>
                </tr>
                @for (int i = 0; i < Model.RachunkiNaRaporcie.Count; i++)
                {
                    <tr style="border:1px solid black">
                        <td style="width:30%;border:1px solid black">
                            @Html.DisplayFor(model => model.RachunkiNaRaporcie.FirstOrDefault().IdRachunku, new { htmlAttributes = new { @class = "form-control intro-input" } })
                        </td>
                        <td style="width:30%;border:1px solid black">
                            @Html.DisplayFor(model => model.RachunkiNaRaporcie.FirstOrDefault().Wysokosc, new { htmlAttributes = new { @class = "form-control intro-input" } })
                        </td>
                        <td style="width:30%;border:1px solid black">
                            @Html.DisplayFor(model => model.RachunkiNaRaporcie.FirstOrDefault().DataRachunku, new { htmlAttributes = new { @class = "form-control intro-input" } })
                        </td>
                        <td style="width:30%;border:1px solid black">
                            @Html.DisplayFor(model => model.RachunkiNaRaporcie.FirstOrDefault().NazwaKasjera, new { htmlAttributes = new { @class = "form-control intro-input" } })
                        </td>
                    </tr>
                }
            </table>
        </div>
        
    </div>
   
</div>

<div class="container-fluid" style="margin-top:20px;">
    <div class="container">
        <div class="row" style="float:left">
            <div class="col-12">
                <button class="btn btn-primary" onclick="@("window.location.href='" + @Url.Action("index", "raporty") + "'");" style="width:100px">Wróć</button>
            </div>
        </div>
    </div>
</div>